# Generated by Django 4.2.9 on 2024-12-07 08:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "запрос",
                "verbose_name_plural": "запросы",
                "default_related_name": "addrequest",
            },
            managers=[
                ("object", login.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("object", login.models.UserManager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=login.models.Profile.image_path,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "block_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата блокировки"
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="попыток входа"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
            managers=[
                ("object", login.models.UserManager()),
            ],
        ),
    ]
