# Generated by Django 4.2.9 on 2024-12-07 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("login", "0002_loginfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginfile",
            name="feedback",
        ),
        migrations.AddField(
            model_name="loginfile",
            name="user",
            field=models.OneToOneField(
                default=int(str(uuid.uuid4().int)[:4]),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
