# Generated by Django 4.2.9 on 2024-12-07 21:01

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_remove_loginfile_feedback_loginfile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=login.models.LoginFile.get_path,
                verbose_name="файл",
            ),
        ),
    ]
