# Generated by Django 4.2.9 on 2024-12-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_competition_budget_competition_is_active"),
        ("login", "0004_alter_loginfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="work_place",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work",
                to="catalog.region",
            ),
            preserve_default=False,
        ),
    ]
