# Generated by Django 4.2.9 on 2024-10-22 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('catalog', '0001_initial'),
        ('catalog', '0002_category_tag_item_is_published_item_text_and_more'),
        ('catalog', '0003_alter_category_options_alter_tag_options_and_more'),
        ('catalog', '0004_alter_category_slug_alter_tag_slug'),
        (
            'catalog',
            '0005_category_canonical_name_item_canonical_name_and_more',
        ),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Имя объекта',
                        max_length=150,
                        verbose_name='Название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Только латинцкие буквы, цифры и знааки _ и -',
                        max_length=200,
                        unique=True,
                        verbose_name='Слаг',
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name='Вес',
                    ),
                ),
                (
                    'canonical_name',
                    models.CharField(
                        help_text='Каноническое название элемента',
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name='Каноническое имя',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Имя объекта',
                        max_length=150,
                        verbose_name='Название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Только латинцкие буквы, цифры и знааки _ и -',
                        max_length=200,
                        unique=True,
                        verbose_name='Слаг',
                    ),
                ),
                (
                    'canonical_name',
                    models.CharField(
                        help_text='Каноническое название элемента',
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name='Каноническое имя',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Имя объекта',
                        max_length=150,
                        verbose_name='Название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Опишите товар',
                        verbose_name='Описание',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='catalog_items',
                        to='catalog.category',
                    ),
                ),
                ('tags', models.ManyToManyField(to='catalog.tag')),
                (
                    'canonical_name',
                    models.CharField(
                        help_text='Каноническое название элемента',
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name='Каноническое имя',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
