# Generated by Django 4.2.9 on 2024-10-24 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('catalog', '0006_alter_category_options_alter_item_options_and_more'),
        ('catalog', '0007_alter_category_canonical_name_and_more'),
    ]

    dependencies = [
        (
            'catalog',
            '0001_initial_squashed_0005_category_canonical_name_item_canonical_name_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='canonical_name',
            field=models.CharField(
                help_text='Каноническое название элемента',
                max_length=150,
                null=True,
                unique=True,
                verbose_name='каноническое имя',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Имя объекта',
                max_length=150,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Только латинцкие буквы, цифры и знааки _ и -',
                max_length=200,
                unique=True,
                verbose_name='слаг',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name='порядок (чем меньше, тем выше)',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='canonical_name',
            field=models.CharField(
                help_text='Каноническое название элемента',
                max_length=150,
                null=True,
                unique=True,
                verbose_name='каноническое имя',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='catalog_items',
                to='catalog.category',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Имя объекта',
                max_length=150,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                help_text='Опишите товар',
                verbose_name='описание',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='canonical_name',
            field=models.CharField(
                help_text='Каноническое название элемента',
                max_length=150,
                null=True,
                unique=True,
                verbose_name='каноническое имя',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Имя объекта',
                max_length=150,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='canonical_name',
            field=models.CharField(
                default='default',
                help_text='Каноническое название элемента',
                max_length=150,
                null=True,
                unique=True,
                verbose_name='каноническое имя',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='canonical_name',
            field=models.CharField(
                default='default',
                help_text='Каноническое название элемента',
                max_length=150,
                null=True,
                unique=True,
                verbose_name='каноническое имя',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='canonical_name',
            field=models.CharField(
                default='default',
                help_text='Каноническое название элемента',
                max_length=150,
                null=True,
                unique=True,
                verbose_name='каноническое имя',
            ),
        ),
    ]
