# Generated by Django 4.2.9 on 2024-10-31 22:04

import catalog.models
import django_ckeditor_5.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        (
            'catalog',
            '0008_alter_item_options_alter_item_category_mainimage_and_more',
        ),
        ('catalog', '0009_alter_item_text'),
        ('catalog', '0010_alter_item_text'),
    ]

    dependencies = [
        (
            'catalog',
            '0006_alter_category_options_alter_item_options_and_more_squashed_0007_alter_category_canonical_name_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={
                'default_related_name': 'items',
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='catalog_items',
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        default=None,
                        upload_to=catalog.models.item_directory_path,
                        verbose_name='изображение',
                    ),
                ),
                (
                    'item',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='main_image',
                        to='catalog.item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'главное изображение',
                'verbose_name_plural': 'главные изображения',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        default=None,
                        upload_to=catalog.models.item_directory_path,
                        verbose_name='изображение',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='catalog.item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(
        'описание',
            help_text=('Опишите товар'),
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(
        'описание',
            help_text=('Описание должно содержать "превосходно" или "роскошно"'),
            ),
        ),
    ]
