# Generated by Django 4.2.9 on 2024-11-23 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0011_item_is_on_main_alter_item_text_squashed_0013_alter_item_created_alter_item_updated",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Age",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Возраст",
                "verbose_name_plural": "Возраста",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Genage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
                (
                    "age",
                    models.ForeignKey(
                        help_text="Выберите Возраст",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_age",
                        to="catalog.age",
                        verbose_name="Возраст",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пол",
                "verbose_name_plural": "Пол",
            },
        ),
        migrations.CreateModel(
            name="Mass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
                (
                    "mass_start",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(1000),
                        ]
                    ),
                ),
                (
                    "mass_end",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(700),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Весовая категория",
                "verbose_name_plural": "Весовые котегории",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
            },
        ),
        migrations.CreateModel(
            name="Range_m",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Диапазон",
                "verbose_name_plural": "Диапозоны",
            },
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
                (
                    "discipline",
                    models.ManyToManyField(
                        help_text="Выберите дисциплину",
                        related_name="catalog_sport",
                        to="catalog.discipline",
                        verbose_name="Дисциплина",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Субъект",
                "verbose_name_plural": "Субъекты",
            },
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя объекта", max_length=150, verbose_name="название"
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        default="default",
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое имя",
                    ),
                ),
                ("params", models.CharField(null=True)),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.RemoveField(
            model_name="image",
            name="item",
        ),
        migrations.RemoveField(
            model_name="mainimage",
            name="item",
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "default_related_name": "items",
                "verbose_name": "мероприятие",
                "verbose_name_plural": "мероприятия",
            },
        ),
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_on_main",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="item",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="item",
            name="text",
        ),
        migrations.RemoveField(
            model_name="item",
            name="updated",
        ),
        migrations.AddField(
            model_name="item",
            name="alert",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Опишите что нужно делать",
                null=True,
                verbose_name="предупреждение",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="number",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(10)]
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="served",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(700),
                    django.core.validators.MinValueValidator(10),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="time",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="MainImage",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="subject",
            name="town",
            field=models.ManyToManyField(to="catalog.town"),
        ),
        migrations.AddField(
            model_name="genage",
            name="gender",
            field=models.ForeignKey(
                help_text="Выберите Пол",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_gen",
                to="catalog.gender",
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="discipline",
            name="gen_age",
            field=models.ManyToManyField(to="catalog.genage"),
        ),
        migrations.AddField(
            model_name="discipline",
            name="mass_cat",
            field=models.ManyToManyField(to="catalog.mass"),
        ),
        migrations.AddField(
            model_name="country",
            name="subject",
            field=models.ManyToManyField(to="catalog.subject"),
        ),
        migrations.AddField(
            model_name="item",
            name="country",
            field=models.ForeignKey(
                help_text="Выберите Страна",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_country",
                to="catalog.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="program",
            field=models.ForeignKey(
                help_text="Выберите Страна",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_program",
                to="catalog.program",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="range_m",
            field=models.ForeignKey(
                help_text="Выберите Страна",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_range_m",
                to="catalog.range_m",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sport",
            field=models.ForeignKey(
                help_text="Выберите дисциплину",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_item",
                to="catalog.discipline",
                verbose_name="Дисциплина",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="subject",
            field=models.ForeignKey(
                help_text="Выберите субект",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_subject",
                to="catalog.subject",
                verbose_name="Субъект",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="town",
            field=models.ForeignKey(
                help_text="Выберите город",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_town",
                to="catalog.town",
                verbose_name="Город",
            ),
        ),
    ]
