# Generated by Django 4.2.9 on 2024-11-23 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_age_country_discipline_genage_gender_mass_program_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="served",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(700),
                    django.core.validators.MinValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mass",
            name="mass_end",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(700),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mass",
            name="mass_start",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
