# Generated by Django 4.2.9 on 2024-12-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_athlete_centralfsp_competition_competitionlevel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="budget",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="is_active",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
